### ISSUE TITLE
OTP Request Unsuccessful on Certain devices

### ISSUE THREAD

**Issue by praveen-gm** [MSG91/sendotp-android#27]
OTP Requests are failing on certain devices when .httpsConnection(false) is set with log **Unsuccessful Try Again**. Most devices that failed when **httpsConnection(false)** were newer devices running Android P and higher. Few phones that were tested on were Nokia 8.1, Nokia 6 etc. But same code were successful on older devices running Android O includes Moto G4, Moto G5s Plus etc. 
When **.httpsConnection(true)** was set to true newer phones worked while older ones failed.

**Comment by IrshadAndroid** [comment]
Thank you for your valuable feedback, given issue has been resolved on new version 1.3.1 .kindly use the new version of SDK [1.3.1](https://github.com/MSG91/sendotp-android)

**Comment by anishmenon** [comment]
Its not fixed we are using latest SDK . OTP is not at all initiating on several devices with old and new android some serious bug with SDK .
